export enum StrategyBoardObject {
    // tab 1
    Tank = 47,
    Tank1 = 48,
    Tank2 = 49,
    Healer = 50,
    Healer1 = 51,
    Healer2 = 52,
    PureHealer = 122,
    BarrierHealer = 123,
    DPS = 53,
    DPS1 = 54,
    DPS2 = 55,
    DPS3 = 56,
    DPS4 = 57,
    MeleeDPS = 118,
    RangedDPS = 119,
    PhysicalRangedDPS = 120,
    MagicalRangedDPS = 121,
    PLD = 27,
    WAR = 29,
    DRK = 38,
    GNB = 43,
    WHM = 32,
    SCH = 35,
    AST = 39,
    SGE = 46,
    MNK = 28,
    DRG = 30,
    NIN = 36,
    SAM = 40,
    RPR = 45,
    VPR = 101,
    BRD = 31,
    MCH = 37,
    DNC = 44,
    BLM = 33,
    SMN = 34,
    RDM = 41,
    PCT = 102,
    BLU = 42,
    GLD = 18,
    MRD = 20,
    CNJ = 23,
    PGL = 19,
    LNC = 21,
    ROG = 26,
    ARC = 22,
    THM = 24,
    ACN = 25,

    // tab 2
    CircleAoE = 9,
    FanAoE = 10,
    LineAoE = 11,
    Gaze = 13,
    Stack = 14,
    LineStack = 15,
    Proximity = 16,
    Donut = 17,
    StackMulti = 106,
    ProximityPlayer = 107,
    Tankbuster = 108,
    RadialKnockback = 109,
    LinearKnockback = 110,
    Tower = 111,
    TargetingIndicator = 112,
    MovingCircleAoE = 126,
    OnePersonAoE = 127,
    TwoPersonAoE = 128,
    ThreePersonAoE = 129,
    FourPersonAoE = 130,

    // tab 3
    SmallEnemy = 60,
    MediumEnemy = 62,
    LargeEnemy = 64,
    Enhancement = 113,
    Enfeeblement = 114,
    Attack1 = 65,
    Attack2 = 66,
    Attack3 = 67,
    Attack4 = 68,
    Attack5 = 69,
    Attack6 = 115,
    Attack7 = 116,
    Attack8 = 117,
    Bind1 = 70,
    Bind2 = 71,
    Bind3 = 72,
    Ignore1 = 73,
    Ignore2 = 74,
    Square = 75,
    Circle = 76,
    Plus = 77,
    Triangle = 78,
    WaymarkA = 79,
    WaymarkB = 80,
    WaymarkC = 81,
    WaymarkD = 82,
    Waymark1 = 83,
    Waymark2 = 84,
    Waymark3 = 85,
    Waymark4 = 86,
    LockOnRed = 131,
    LockOnBlue = 132,
    LockOnPurple = 133,
    LockOnGreen = 134,

    // tab 4
    Text = 100,
    SymbolCircle = 87,
    SymbolCross = 88,
    SymbolTriangle = 89,
    SymbolSquare = 90,
    UpArrow = 94,
    Rotate = 103,
    HighlightedCircle = 135,
    HighlightedCross = 136,
    HighlightedSquare = 137,
    HighlightedTriangle = 138,
    RotateCW = 139,
    RotateCCW = 140,
    Line = 12,

    // tab 5
    BGCheckeredCircle = 4,
    BGCheckeredSquare = 8,
    BGGrayCircle = 124,
    BGGraySquare = 125
}

export const defaultObjectScale = 1 / 200;

export interface SpriteParameters {
    image?: string;
    size?: number;
    offset?: number;
    scale?: number;
    special?: boolean;
}

export const spriteParameters: { [key: number]: SpriteParameters } = {
    // tab 1
    [StrategyBoardObject.Tank]: { image: 'assets/objects/tab1', size: 128, offset: 0 },
    [StrategyBoardObject.Tank1]: { image: 'assets/objects/tab1', size: 128, offset: 128 },
    [StrategyBoardObject.Tank2]: { image: 'assets/objects/tab1', size: 128, offset: 256 },
    [StrategyBoardObject.Healer]: { image: 'assets/objects/tab1', size: 128, offset: 384 },
    [StrategyBoardObject.Healer1]: { image: 'assets/objects/tab1', size: 128, offset: 512 },
    [StrategyBoardObject.Healer2]: { image: 'assets/objects/tab1', size: 128, offset: 640 },
    [StrategyBoardObject.PureHealer]: { image: 'assets/objects/tab1', size: 128, offset: 768 },
    [StrategyBoardObject.BarrierHealer]: { image: 'assets/objects/tab1', size: 128, offset: 896 },
    [StrategyBoardObject.DPS]: { image: 'assets/objects/tab1', size: 128, offset: 1024 },
    [StrategyBoardObject.DPS1]: { image: 'assets/objects/tab1', size: 128, offset: 1152 },
    [StrategyBoardObject.DPS2]: { image: 'assets/objects/tab1', size: 128, offset: 1280 },
    [StrategyBoardObject.DPS3]: { image: 'assets/objects/tab1', size: 128, offset: 1408 },
    [StrategyBoardObject.DPS4]: { image: 'assets/objects/tab1', size: 128, offset: 1536 },
    [StrategyBoardObject.MeleeDPS]: { image: 'assets/objects/tab1', size: 128, offset: 1664 },
    [StrategyBoardObject.RangedDPS]: { image: 'assets/objects/tab1', size: 128, offset: 1792 },
    [StrategyBoardObject.PhysicalRangedDPS]: { image: 'assets/objects/tab1', size: 128, offset: 1920 },
    [StrategyBoardObject.MagicalRangedDPS]: { image: 'assets/objects/tab1', size: 128, offset: 2048 },
    [StrategyBoardObject.PLD]: { image: 'assets/objects/tab1', size: 128, offset: 2176 },
    [StrategyBoardObject.WAR]: { image: 'assets/objects/tab1', size: 128, offset: 2304 },
    [StrategyBoardObject.DRK]: { image: 'assets/objects/tab1', size: 128, offset: 2432 },
    [StrategyBoardObject.GNB]: { image: 'assets/objects/tab1', size: 128, offset: 2560 },
    [StrategyBoardObject.WHM]: { image: 'assets/objects/tab1', size: 128, offset: 2688 },
    [StrategyBoardObject.SCH]: { image: 'assets/objects/tab1', size: 128, offset: 2816 },
    [StrategyBoardObject.AST]: { image: 'assets/objects/tab1', size: 128, offset: 2944 },
    [StrategyBoardObject.SGE]: { image: 'assets/objects/tab1', size: 128, offset: 3072 },
    [StrategyBoardObject.MNK]: { image: 'assets/objects/tab1', size: 128, offset: 3200 },
    [StrategyBoardObject.DRG]: { image: 'assets/objects/tab1', size: 128, offset: 3328 },
    [StrategyBoardObject.NIN]: { image: 'assets/objects/tab1', size: 128, offset: 3456 },
    [StrategyBoardObject.SAM]: { image: 'assets/objects/tab1', size: 128, offset: 3584 },
    [StrategyBoardObject.RPR]: { image: 'assets/objects/tab1', size: 128, offset: 3712 },
    [StrategyBoardObject.VPR]: { image: 'assets/objects/tab1', size: 128, offset: 3840 },
    [StrategyBoardObject.BRD]: { image: 'assets/objects/tab1', size: 128, offset: 3968 },
    [StrategyBoardObject.MCH]: { image: 'assets/objects/tab1', size: 128, offset: 4096 },
    [StrategyBoardObject.DNC]: { image: 'assets/objects/tab1', size: 128, offset: 4224 },
    [StrategyBoardObject.BLM]: { image: 'assets/objects/tab1', size: 128, offset: 4352 },
    [StrategyBoardObject.SMN]: { image: 'assets/objects/tab1', size: 128, offset: 4480 },
    [StrategyBoardObject.RDM]: { image: 'assets/objects/tab1', size: 128, offset: 4608 },
    [StrategyBoardObject.PCT]: { image: 'assets/objects/tab1', size: 128, offset: 4736 },
    [StrategyBoardObject.BLU]: { image: 'assets/objects/tab1', size: 128, offset: 4864 },
    [StrategyBoardObject.GLD]: { image: 'assets/objects/tab1', size: 128, offset: 4992 },
    [StrategyBoardObject.MRD]: { image: 'assets/objects/tab1', size: 128, offset: 5120 },
    [StrategyBoardObject.CNJ]: { image: 'assets/objects/tab1', size: 128, offset: 5248 },
    [StrategyBoardObject.PGL]: { image: 'assets/objects/tab1', size: 128, offset: 5376 },
    [StrategyBoardObject.LNC]: { image: 'assets/objects/tab1', size: 128, offset: 5504 },
    [StrategyBoardObject.ROG]: { image: 'assets/objects/tab1', size: 128, offset: 5632 },
    [StrategyBoardObject.ARC]: { image: 'assets/objects/tab1', size: 128, offset: 5760 },
    [StrategyBoardObject.THM]: { image: 'assets/objects/tab1', size: 128, offset: 5888 },
    [StrategyBoardObject.ACN]: { image: 'assets/objects/tab1', size: 128, offset: 6016 },

    // tab 2
    [StrategyBoardObject.CircleAoE]: { image: 'assets/objects/circle_aoe', scale: 1 / 100 },
    [StrategyBoardObject.FanAoE]: { special: true },
    [StrategyBoardObject.LineAoE]: { special: true },
    [StrategyBoardObject.Gaze]: { image: 'assets/objects/tab2', size: 512, offset: 0 },
    [StrategyBoardObject.Stack]: { image: 'assets/objects/tab2', size: 512, offset: 512 },
    [StrategyBoardObject.LineStack]: { image: 'assets/objects/tab2', size: 512, offset: 1024 },
    [StrategyBoardObject.Proximity]: { image: 'assets/objects/tab2', size: 512, offset: 1536, scale: 1 / 100 },
    [StrategyBoardObject.Donut]: { special: true },
    [StrategyBoardObject.StackMulti]: { image: 'assets/objects/tab2', size: 512, offset: 2048 },
    [StrategyBoardObject.ProximityPlayer]: { image: 'assets/objects/tab2', size: 512, offset: 2560 },
    [StrategyBoardObject.Tankbuster]: { image: 'assets/objects/tab2', size: 512, offset: 3072, scale: 1 / 400 },
    [StrategyBoardObject.RadialKnockback]: { image: 'assets/objects/tab2', size: 512, offset: 3584, scale: 1 / 100 },
    [StrategyBoardObject.LinearKnockback]: { image: 'assets/objects/tab2', size: 512, offset: 4096, scale: 1 / 100 },
    [StrategyBoardObject.Tower]: { image: 'assets/objects/tab2', size: 512, offset: 4608, scale: 1 / 400 },
    [StrategyBoardObject.TargetingIndicator]: { image: 'assets/objects/tab2', size: 512, offset: 5120, scale: 1 / 400 },
    [StrategyBoardObject.MovingCircleAoE]: { image: 'assets/objects/tab2', size: 512, offset: 5632 },
    [StrategyBoardObject.OnePersonAoE]: { image: 'assets/objects/tab2', size: 512, offset: 6144, scale: 1 / 400 },
    [StrategyBoardObject.TwoPersonAoE]: { image: 'assets/objects/tab2', size: 512, offset: 6656, scale: 1 / 400 },
    [StrategyBoardObject.ThreePersonAoE]: { image: 'assets/objects/tab2', size: 512, offset: 7168, scale: 1 / 400 },
    [StrategyBoardObject.FourPersonAoE]: { image: 'assets/objects/tab2', size: 512, offset: 7680, scale: 1 / 400 },

    // tab 3
    [StrategyBoardObject.SmallEnemy]: { image: 'assets/objects/tab3', size: 128, offset: 0, scale: 1 / 100 },
    [StrategyBoardObject.MediumEnemy]: { image: 'assets/objects/tab3', size: 128, offset: 128, scale: 1 / 100 },
    [StrategyBoardObject.LargeEnemy]: { image: 'assets/objects/tab3', size: 128, offset: 256, scale: 1 / 100 },
    [StrategyBoardObject.Enhancement]: { image: 'assets/objects/tab3', size: 128, offset: 384 },
    [StrategyBoardObject.Enfeeblement]: { image: 'assets/objects/tab3', size: 128, offset: 512 },
    [StrategyBoardObject.Attack1]: { image: 'assets/objects/tab3', size: 96, offset: 640, scale: 1 / 150 },
    [StrategyBoardObject.Attack2]: { image: 'assets/objects/tab3', size: 96, offset: 736, scale: 1 / 150 },
    [StrategyBoardObject.Attack3]: { image: 'assets/objects/tab3', size: 96, offset: 832, scale: 1 / 150 },
    [StrategyBoardObject.Attack4]: { image: 'assets/objects/tab3', size: 96, offset: 928, scale: 1 / 150 },
    [StrategyBoardObject.Attack5]: { image: 'assets/objects/tab3', size: 96, offset: 1024, scale: 1 / 150 },
    [StrategyBoardObject.Attack6]: { image: 'assets/objects/tab3', size: 96, offset: 1120, scale: 1 / 150 },
    [StrategyBoardObject.Attack7]: { image: 'assets/objects/tab3', size: 96, offset: 1216, scale: 1 / 150 },
    [StrategyBoardObject.Attack8]: { image: 'assets/objects/tab3', size: 96, offset: 1312, scale: 1 / 150 },
    [StrategyBoardObject.Bind1]: { image: 'assets/objects/tab3', size: 96, offset: 1408, scale: 1 / 150 },
    [StrategyBoardObject.Bind2]: { image: 'assets/objects/tab3', size: 96, offset: 1504, scale: 1 / 150 },
    [StrategyBoardObject.Bind3]: { image: 'assets/objects/tab3', size: 96, offset: 1600, scale: 1 / 150 },
    [StrategyBoardObject.Ignore1]: { image: 'assets/objects/tab3', size: 96, offset: 1696, scale: 1 / 150 },
    [StrategyBoardObject.Ignore2]: { image: 'assets/objects/tab3', size: 96, offset: 1792, scale: 1 / 150 },
    [StrategyBoardObject.Square]: { image: 'assets/objects/tab3', size: 96, offset: 1888, scale: 1 / 150 },
    [StrategyBoardObject.Circle]: { image: 'assets/objects/tab3', size: 96, offset: 1984, scale: 1 / 150 },
    [StrategyBoardObject.Plus]: { image: 'assets/objects/tab3', size: 96, offset: 2080, scale: 1 / 150 },
    [StrategyBoardObject.Triangle]: { image: 'assets/objects/tab3', size: 96, offset: 2176, scale: 1 / 150 },
    [StrategyBoardObject.WaymarkA]: { image: 'assets/objects/tab3', size: 96, offset: 2272, scale: 1 / 100 },
    [StrategyBoardObject.WaymarkB]: { image: 'assets/objects/tab3', size: 96, offset: 2368, scale: 1 / 100 },
    [StrategyBoardObject.WaymarkC]: { image: 'assets/objects/tab3', size: 96, offset: 2464, scale: 1 / 100 },
    [StrategyBoardObject.WaymarkD]: { image: 'assets/objects/tab3', size: 96, offset: 2560, scale: 1 / 100 },
    [StrategyBoardObject.Waymark1]: { image: 'assets/objects/tab3', size: 96, offset: 2656, scale: 1 / 100 },
    [StrategyBoardObject.Waymark2]: { image: 'assets/objects/tab3', size: 96, offset: 2752, scale: 1 / 100 },
    [StrategyBoardObject.Waymark3]: { image: 'assets/objects/tab3', size: 96, offset: 2848, scale: 1 / 100 },
    [StrategyBoardObject.Waymark4]: { image: 'assets/objects/tab3', size: 96, offset: 2944, scale: 1 / 100 },
    [StrategyBoardObject.LockOnRed]: { image: 'assets/objects/tab3', size: 96, offset: 3040, scale: 1 / 100 },
    [StrategyBoardObject.LockOnBlue]: { image: 'assets/objects/tab3', size: 96, offset: 3136, scale: 1 / 100 },
    [StrategyBoardObject.LockOnPurple]: { image: 'assets/objects/tab3', size: 96, offset: 3232, scale: 1 / 100 },
    [StrategyBoardObject.LockOnGreen]: { image: 'assets/objects/tab3', size: 96, offset: 3328, scale: 1 / 100 },

    // tab 4
    [StrategyBoardObject.Text]: { special: true },
    [StrategyBoardObject.SymbolCircle]: { image: 'assets/objects/tab4', size: 96, offset: 0, scale: 1 / 100 },
    [StrategyBoardObject.SymbolCross]: { image: 'assets/objects/tab4', size: 96, offset: 96, scale: 1 / 100 },
    [StrategyBoardObject.SymbolTriangle]: { image: 'assets/objects/tab4', size: 96, offset: 192, scale: 1 / 100 },
    [StrategyBoardObject.SymbolSquare]: { image: 'assets/objects/tab4', size: 96, offset: 288, scale: 1 / 100 },
    [StrategyBoardObject.UpArrow]: { image: 'assets/objects/tab4', size: 96, offset: 384, scale: 1 / 100 },
    [StrategyBoardObject.Rotate]: { image: 'assets/objects/tab4', size: 96, offset: 480, scale: 1 / 100 },
    [StrategyBoardObject.HighlightedCircle]: { image: 'assets/objects/tab4', size: 96, offset: 576, scale: 1 / 100 },
    [StrategyBoardObject.HighlightedCross]: { image: 'assets/objects/tab4', size: 96, offset: 672, scale: 1 / 100 },
    [StrategyBoardObject.HighlightedSquare]: { image: 'assets/objects/tab4', size: 96, offset: 768, scale: 1 / 100 },
    [StrategyBoardObject.HighlightedTriangle]: { image: 'assets/objects/tab4', size: 96, offset: 864, scale: 1 / 100 },
    [StrategyBoardObject.RotateCW]: { image: 'assets/objects/tab4', size: 96, offset: 960, scale: 1 / 100 },
    [StrategyBoardObject.RotateCCW]: { image: 'assets/objects/tab4', size: 96, offset: 1056, scale: 1 / 100 },
    [StrategyBoardObject.Line]: { special: true },

    // tab 5
    [StrategyBoardObject.BGCheckeredCircle]: { image: 'assets/objects/tab5', size: 512, offset: 0, scale: 1 / 100 },
    [StrategyBoardObject.BGCheckeredSquare]: { image: 'assets/objects/tab5', size: 512, offset: 512, scale: 1 / 100 },
    [StrategyBoardObject.BGGrayCircle]: { image: 'assets/objects/tab5', size: 512, offset: 1024, scale: 1 / 100 },
    [StrategyBoardObject.BGGraySquare]: { image: 'assets/objects/tab5', size: 512, offset: 1536, scale: 1 / 100 }
};
